name: telecom_churn_dbt_project

profile: telecom_churn_dbt_project

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  telecom_churn_dbt_project:
    +schema: raw

models:
  telecom_churn_dbt_project:
    +static_analysis: strict
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
